# Control center configuration
*control_center_config: &control_center_config  # Define the anchor
  build:
    context: .
    dockerfile: Dockerfile
  ports:
    - "5000:5000"
  depends_on:
    - db
  networks:
    - dgd_network

networks:
  dgd_network:
    # This network will be created automatically
