version: "3.9"

services:
  control_center:
    <<: *control_center_config 

  db:
    <<: *db_config

  vulnerability_scanner:
    <<: *vulnerability_scanner_config 

networks:
  dgd_network:
    # This network will be created automatically
