version: "3.9"

services:
  control_center:
    <<: *control_center_config
    env_file:
      - .env

  db:
    <<: *db_config
    env_file:
      - .env

  vulnerability_scanner:
    <<: *vulnerability_scanner_config
    env_file:
      - .env

networks:
  dgd_network:
    # This network will be created automatically
