version: "3.9"

services:
  control_center:
    build:
      context: ./control_center
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Expose Flask app on port 5000
    volumes:
      - ./control_center:/app  # Mount the control_center folder
    env_file:
      - .env  # Use environment variables from the .env file
    depends_on:
      - db
    networks:
      - dgd_network

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/postgresql/data  # Ensure database data persists
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialize the database
    env_file:
      - .env  # Use environment variables for DB credentials
    ports:
      - "5432:5432"  # Expose the database port
    networks:
      - dgd_network



networks:
  dgd_network:
    driver: bridge

volumes:
  db_data:
    driver: local
