version: "3.9"

services:
  control_center:
    <<: *control_center_config
    env_file:
      - ./.env  # Load the centralized env file

  db:
    <<: *db_config
    env_file:
      - ./.env  # Load the centralized env file

  vulnerability_scanner:
    <<: *vulnerability_scanner_config

networks:
  dgd_network:
    # This network will be created automatically
