*vulnerability_scanner_config: &vulnerability_scanner_config  # Define the anchor
  build:
    context: .
    dockerfile: Dockerfile
  networks:
    - host_network
    - dgd_network

networks:
  host_network:
    external: true
    name: host
  dgd_network:
    # This network will be created automatically
