services:
  vulnerability_scanner:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    networks:
      - host_network
      - dgd_network

networks:
  host_network:
    external: true
    name: host
  dgd_network:
    # This network will be created automatically
